### PR TITLE
Add Transformer matching logic

### PR DESCRIPTION
**Pull request by codewithcheese**
Adapted from product-os/jellyfish-worker
Rewrote logic to be more readable.
Added tests for better coverage.

Change-type: minor

### CODE REVIEW

**Comment by codewithcheese** [comment]
Any idea why the node tests are not running on the PRs?

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
Is your plan to have `jellyfish-worker` import this matching logic?

**Comment by codewithcheese** [comment]
@balena-ci I self-certify!

**Pull request merged**
